Configure Dependabot for version updates

- Set up Dependabot to manage version updates for the project.
- Specify the package ecosystem and directory for package manifests.
- Schedule updates to run weekly.
